name: firebase_web
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  cloud_firestore: ^4.17.2
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  firebase_performance: ^0.9.4+5
  firebase_storage: ^11.7.5
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_dotenv: ^5.1.0
  go_router: ^14.0.1
  google_sign_in: ^6.2.1
  image_network: ^2.5.6
  image_picker: ^1.1.1
  permission_handler: ^11.3.1
  provider: ^6.1.2
  random_string: ^2.3.1
  shared_preferences: ^2.2.3

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
